apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.name }}-migrate"
spec:
  template:
    metadata:
      name: "{{ .Values.name }}-migrate"
    spec:
      restartPolicy: Never
      {{ if .Values.postgres.install }}
      initContainers:
      - name: wait-for-postgres-connection
        image: {{ .Values.postgres.postgresql.image }}
        imagePullPolicy: {{ .Values.postgres.postgresql.imagePullPolicy }}
        args:
          - "pod"
          - "postgresql-0"
      {{ end }}
      containers:
      - name: "{{ .Values.name }}-migrate"
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default .Chart.AppVersion }}"
        command: ["/bin/sh"]
        args: ["-c", "npm run migrate:up"]
        env:
        - name: POSTGRESQL_URL
          value: "postgresql://{{ .Values.postgres.postgresqlUsername}}:{{ .Values.postgres.postgresqlPassword}}@{{ .Values.postgres.domain}}:{{ .Values.postgres.postgresqlPort}}/{{ .Values.postgres.db}}?sslmode=disable"