name: amplication-storage-gateway

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
image:
  pullPolicy: Always
  repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-storage-gateway
  tag: 0.0.1
  imagePullSecrets: []

volume:
  name: amplication-data
  path: /amplication-data

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

maxMemory: "1.6Gi"
minMemory: "1.6Gi"
maxCPU: "0.9"
minCPU: "0.9"

service:
  type: ClusterIP
  port:
    target: 3002
  protocol: TCP

ingress:
  enabled: true
  hostname: server.amplication.com
  path: /storage
