apiVersion: v1
kind: PersistentVolume
metadata:
  name: dsg-jobs-{{ .Values.envName }}-dsg
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.persistentVolume.volumeHandle }}"
