apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-pod-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: batch/v1
              kind: Job
              metadata:
                generateName: dsg-job-
              spec:
                template:
                  spec:
                    nodeSelector:
                      role: dsg
                    tolerations:
                      - key: dedicated
                        value: dsg
                    restartPolicy: Never
                    containers:
                      - name: dsg-container
                        image: "407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-data-service-generator:0.0.13"
                        command: ["sh", "-c"]
                        args:
                          [
                            "cd /app/packages/amplication-data-service-generator; npm run generate-code -- /efs/input.json /efs/output",
                          ]
                        env:
                          - name: BUILD_ID
                            value: null # provided in parameters
                          - name: STATUS_UPDATE_URL
                            value: http://amplication-build-manager.next.svc.cluster.local/build-runner/complete-code-generation-step
                          - name: CREATE_LOG_URL
                            value: http://amplication-build-manager.next.svc.cluster.local/build-logger/create-log
                        volumeMounts:
                          - name: persistent-storage
                            mountPath: /efs
                            subPathExpr: build-data/$(BUILD_ID)
                    volumes:
                      - name: persistent-storage
                        persistentVolumeClaim:
                          claimName: efs-claim-{{ .Values.envName }}-dsg
                ttlSecondsAfterFinished:
                  { { .Values.job.ttlSecondsAfterFinished } }
                backoffLimit: 0
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.buildId
              dest: spec.template.spec.containers.0.env.0.value
