name: amplication-server

autoscaling:
  enabled: enabled
  minReplicas: 2
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
replicaCount: 2
image:
  pullPolicy: Always
  repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-prod-server
  tag: 0.0.7
  imagePullSecrets: []

service:
  type: ClusterIP
  port: 
    target: 3000
  protocol: TCP
ingress:
  enabled: true
  hostname: server.amplication-dev.com

secrets:
  GPC: ""

pvc:
  storageLimit: 5Gi
  storageRequest: 1Gi
  name: efs-claim
  storageName: efs-sc

# Postgresql Server
postgres:
  install: false
  postgresqlUsername: postgres
  postgresPassword: postgres
  db: amplication
  fullnameOverride: postgresql
  postgresql:
    image: groundnuty/k8s-wait-for:v1.3
    imagePullPolicy: Always
    primary:
      podLabels: { name: "postgres" }