name: amplication-server

deployment:
  replicaCount: 2
  volume:
    name: amplication-server-artifacts-data
    path: /artifacts
  autoscaling:
    enabled: enabled
    minReplicas: 2
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  podAnnotations: {}
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  image:
    pullPolicy: Always
    repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-prod-server
    tag: 0.0.7
    imagePullSecrets: []

service:
  type: ClusterIP
  port: 
    target: 3000
  protocol: TCP
ingress:
  enabled: true
  hostname: server.amplication-dev.com

secrets:
  GPC: ""

pvc:
  storageLimit: 5Gi
  storageRequest: 1Gi

# Postgresql Server
postgres:
  install: false
  postgresqlUsername: postgres
  postgresPassword: postgres
  db: amplication
  fullnameOverride: postgresql
  postgresql:
    image: groundnuty/k8s-wait-for:v1.3
    imagePullPolicy: Always
    primary:
      podLabels: { name: "postgres" }
