pvc:
  name: efs-claim
  storageRequest: 1Gi
  storageName: efs-sc

pv:
  name: efs-pv-custom
  handle: fs-03a0a5ba30d788595::fsap-08494d4659781878b

dsg-pvc:
  name: dsg-efs-pvc
  storageRequest: 1Gi
  storageName: efs-sc

dsg-pv:
  name: dsg-efs-pv
  handle: fs-0a5d600fe9ec1387f::fsap-0c0986f263735b48c
