apiVersion: v1
kind: Service
metadata:
  name: amplication-build-manager
  namespace: {{ .Release.Namespace }}-dsg
  labels:
    app: amplication-build-manager
spec:
  selector:
    app: amplication-build-manager
  ports:
    - name: http
      protocol: TCP
      port: 80
