envName: "staging"

job:
  ttlSecondsAfterFinished: 1800
  image: 
    repository: "407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-data-service-generator-runner"
    tag: "master"

dsgJobsPv:
  name: dsg-jobs-staging-dsg
  volumeHandle: fs-0a5d600fe9ec1387f::fsap-0c0986f263735b48c

buildArtifactsPv:
  name: build-artifacts-staging-dsg
  volumeHandle: fs-03a0a5ba30d788595::fsap-08494d4659781878b

amplication-build-manager:
  config:
    env:
      PORT: "80"

      KAFKA_BROKERS: 'b-1.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092,b-2.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092'
      KAFKA_CLIENT_ID: build-manager
      KAFKA_GROUP_ID: build-manager

      CREATE_PR_REQUEST_TOPIC: git.internal.create-pr.request.1

      CODE_GENERATION_REQUEST_TOPIC: build.internal.code-generation.request.1
      CODE_GENERATION_SUCCESS_TOPIC: build.internal.code-generation.success.1
      CODE_GENERATION_FAILURE_TOPIC: build.internal.code-generation.failure.1

      DSG_LOG_TOPIC: build.internal.dsg-log.1

      DSG_RUNNER_URL: http://webhook-eventsource-svc.staging-dsg.svc.cluster.local:12000/example

      BUILD_ARTIFACTS_BASE_FOLDER: /build-artifacts/build-data
      BUILD_ARTIFACTS_CODE_FOLDER: code

      DSG_JOBS_BASE_FOLDER: /dsg-jobs
      DSG_JOBS_CODE_FOLDER: code
      DSG_JOBS_RESOURCE_DATA_FILE: input.json
