name: amplication-git-pull-request-service


replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
image:
  pullPolicy: Always
  repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-git-pull-request-service-dev
  tag: 0.0.1
  imagePullSecrets: []

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

maxMemory: 2
minMemory: 2
maxCPU: 2
minCPU: 2

volume:
  name: amplication-data
  path: /amplication-data

service:
  type: ClusterIP
  port:
    target: 3000
  protocol: TCP

ingress:
  enabled: false

pvc:
  storageRequest: 1Gi
  storageName: efs-sc
  name: efs-claim