global:
  pvc:
    name: alex-efs-claim
  pv:
    name: efs-pv-alex
  nodeSelector:
    role: custom-envs
  tolerations:
    - key: "custom-envs"
      operator: "Equal"
      value: "true"

postgres:
  primary:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres-alex.amplication-dev.com

amplication-client:
  service:
    hostname: app-alex.amplication-dev.com
  config:
    env:
      REACT_APP_SERVER_URI: "https://server-alex.amplication-dev.com"
      REACT_APP_DATA_SOURCE: "https://server-alex.amplication-dev.com/graphql"
      REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server-alex.amplication-dev.com/github"
      REACT_APP_STORAGE_GATEWAY_URL: https://server-alex.amplication-dev.com

amplication-server:
  ingress:
    hostname: server-alex.amplication-dev.com
  config:
    env:
      HOST: "https://server-alex.amplication-dev.com"
      CLIENT_HOST: "https://app-alex.amplication-dev.com"

      #KAFKA
      KAFKA_BROKERS: '["amplication-alex-cp-kafka-headless:9092"]'

      #GitHub App
      GITHUB_APP_APP_ID: "217654"
      GITHUB_APP_CLIENT_ID: "Iv1.6aca4dc2d00fbedf"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/alex-bass-github-app/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "b792d890f40f60170c82"
      GITHUB_REDIRECT_URI: "https://server-alex.amplication-dev.com/github/callback"

amplication-git-push-webhook-service:
  ingress:
    hostname: webhook-alex.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-alex-cp-kafka-headless:9092"]'

amplication-git-pull-service:
  config:
    env:
      NODE_ENV: "production"

      #EFS
      STORAGE_PATH: /amplication-data/git-data
      MAX_SNAPSHOTS: "100"

      #GitHub App
      GIT_DEFAULT_ORIGIN_NAME: origin
      GITHUB_APP_APP_ID: "217654"
      GITHUB_APP_CLIENT_ID: "Iv1.6aca4dc2d00fbedf"
      KAFKA_BROKERS: '["amplication-alex-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: git-pull-service
      KAFKA_GROUP_ID: git-pull-service-group

      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS: '["amplication-alex-cp-kafka-headless:9092"]'
      GITHUB_APP_APP_ID: "217654"

amplication-storage-gateway:
  ingress:
    hostname: server-alex.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-alex-cp-kafka-headless:9092"]'
      GITHUB_APP_APP_ID: "217654"
