global:
  pvc:
    name: build-artifacts
    storageRequest: 5Gi
    storageName: efs-sc
  pv:
    name: build-artifacts-staging
    storageCapacity: 5Gi
    handle: fs-03a0a5ba30d788595::fsap-08494d4659781878b

  nodeSelector:
    role: custom-envs
  tolerations:
    - key: "custom-envs"
      operator: "Equal"
      value: "true"

postgres:
  primary:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres-staging.amplication-dev.com

amplication-client:
  service:
    hostname: app.staging.amplication-dev.com
    certificatearn: arn:aws:acm:us-east-1:407256539111:certificate/28d98c3b-f831-4cfd-b71b-577f9f7a5d45
  config:
    env:
      NX_REACT_APP_SERVER_URI: "https://server.staging.amplication-dev.com"
      NX_REACT_APP_DATA_SOURCE: "https://server.staging.amplication-dev.com/graphql"
      NX_REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server.staging.amplication-dev.com/github"
      NX_REACT_APP_STORAGE_GATEWAY_URL: https://server.staging.amplication-dev.com

amplication-server:
  autoscaling:
    minReplicas: 12
    maxReplicas: 99
  replicaCount: 12
  ingress:
    hostname: server.staging.amplication-dev.com
  config:
    env:
      HOST: "https://server.staging.amplication-dev.com"
      CLIENT_HOST: "https://app.staging.amplication-dev.com"

      #KAFKA
      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
      KAFKA_BROKERS: 'b-1.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092,b-2.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092'
      KAFKA_CLIENT_ID: amplication-server
      KAFKA_GROUP_ID: amplication-server-group

      CREATE_PR_REQUEST_TOPIC: git.internal.create-pr.request.1
      CREATE_PR_SUCCESS_TOPIC: git.internal.create-pr.success.1
      CREATE_PR_FAILURE_TOPIC: git.internal.create-pr.failure.1

      CODE_GENERATION_REQUEST_TOPIC: build.internal.code-generation.request.1
      CODE_GENERATION_SUCCESS_TOPIC: build.internal.code-generation.success.1
      CODE_GENERATION_FAILURE_TOPIC: build.internal.code-generation.failure.1

      DSG_LOG_TOPIC: build.internal.dsg-log.1

      DOCKER_HOST: tcp://docker:2375

      DSG_RUNNER_URL: http://webhook-eventsource-svc.staging-dsg.svc.cluster.local:12000/example

      #GitHub App
      GITHUB_APP_APP_ID: "174833"
      GITHUB_APP_CLIENT_ID: "Iv1.e0d76b0ce191a528"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/amplication-staging/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "4f5b9a88cf46d4c5ec32"
      GITHUB_SECRET_SECRET_NAME: "projects/948093699220/secrets/github-secret-amplication-aws/versions/1"
      GITHUB_REDIRECT_URI: "https://server.staging.amplication-dev.com/github/callback"

amplication-git-push-webhook-service:
  ingress:
    hostname: webhook.staging.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: 'b-1.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092,b-2.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092'
      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0
      KAFKA_CLIENT_ID: git-push-webhook-service
      KAFKA_GROUP_ID: amplication-git-push-webhook-service
      GITHUB_APP_APP_ID: "174833"
      GITHUB_APP_CLIENT_ID: "Iv1.e0d76b0ce191a528"

amplication-git-pull-service:
  config:
    env:
      NODE_ENV: "production"

      #EFS
      STORAGE_PATH: /amplication-data/git-data
      MAX_SNAPSHOTS: "100"

      #GitHub App
      GITHUB_APP_APP_ID: "174833"
      GITHUB_APP_CLIENT_ID: "Iv1.e0d76b0ce191a528"
      GIT_DEFAULT_ORIGIN_NAME: origin
      GITHUB_APP_PRIVATE_KEY: ""

      KAFKA_BROKERS: 'b-1.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092,b-2.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092'
      KAFKA_CLIENT_ID: git-pull-service
      KAFKA_GROUP_ID: git-pull-service-group

      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0

amplication-git-pull-request-service:
  autoscaling:
    minReplicas: 4
    maxReplicas: 12
  config:
    env:
      KAFKA_BROKERS: 'b-1.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092,b-2.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092'
      KAFKA_CLIENT_ID: git-pull-request-service
      KAFKA_GROUP_ID: git-pull-request-service-group

      CREATE_PR_REQUEST_TOPIC: git.internal.create-pr.request.1
      CREATE_PR_SUCCESS_TOPIC: git.internal.create-pr.success.1
      CREATE_PR_FAILURE_TOPIC: git.internal.create-pr.failure.1

      BUILD_ARTIFACTS_BASE_FOLDER: /amplication-data/build-data
      BUILD_ARTIFACTS_CODE_FOLDER: code

      GITHUB_APP_APP_ID: "174833"

amplication-storage-gateway:
  ingress:
    hostname: server.staging.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: 'b-1.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092,b-2.amplicationuseast1sta.n74l10.c22.kafka.us-east-1.amazonaws.com:9092'
      BUILD_ARTIFACTS_BASE_FOLDER: /amplication-data/build-data
      BUILD_ARTIFACTS_CODE_FOLDER: code
      GITHUB_APP_APP_ID: "174833"

