global:
  pvc:
    name: next-efs-claim
  pv:
    name: efs-pv-next
  nodeSelector:
    role: custom-envs
  tolerations:
    - key: "custom-envs"
      operator: "Equal"
      value: "true"

postgres:
  primary:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres-next.amplication-dev.com

amplication-client:
  service:
    hostname: app-next.amplication-dev.com
  config:
    env:
      REACT_APP_SERVER_URI: "https://server-next.amplication-dev.com"
      REACT_APP_DATA_SOURCE: "https://server-next.amplication-dev.com/graphql"
      REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server-next.amplication-dev.com/github"
      REACT_APP_STORAGE_GATEWAY_URL: https://server-next.amplication-dev.com

amplication-server:
  autoscaling:
    minReplicas: 4
    maxReplicas: 99
  replicaCount: 4
  ingress:
    hostname: server-next.amplication-dev.com
  config:
    env:
      HOST: "https://server-next.amplication-dev.com"
      CLIENT_HOST: "https://app-next.amplication-dev.com"

      #KAFKA
      KAFKA_BROKERS: '["amplication-next-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: amplication-server
      KAFKA_GROUP_ID: amplication-server-group

      CREATE_PR_REQUEST_TOPIC: internal.create-pr.request.0
      CREATE_PR_SUCCESS_TOPIC: internal.create-pr.success.0
      CREATE_PR_FAILURE_TOPIC: internal.create-pr.failure.0
      CODE_GENERATION_REQUEST_TOPIC: internal.code-generation.request.0
      CODE_GENERATION_SUCCESS_TOPIC: internal.code-generation.success.0
      CODE_GENERATION_FAILURE_TOPIC: internal.code-generation.failure.0

      #EFS
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      BUILD_INPUT_FILE_NAME: input.json

      #GCP - APPS Builder
      DEFAULT_DISK: gcs
      LOCAL_DISK_ROOT: /artifacts
      CONTAINER_BUILDER_DEFAULT: cloud-build
      GCS_BUCKET: amplication-artifacts

      #GCP - APPS Deployer
      DEPLOYER_DEFAULT: gcp

      GCP_APPS_PROJECT_ID: amplication-apps
      GCP_APPS_REGION: us-east1
      GCP_APPS_TERRAFORM_STATE_BUCKET: amplication-apps-state-bucket
      GCP_APPS_DATABASE_INSTANCE: apps-database-instance
      GCP_APPS_DOMAIN: staging.amplication.app

      DOCKER_HOST: tcp://docker:2375

      DSG_RUNNER_URL: http://webhook-eventsource-svc.next-dsg.svc.cluster.local:12000/example

      #GitHub App
      GITHUB_APP_APP_ID: "225471"
      GITHUB_APP_CLIENT_ID: "Iv1.ba108fc312eb8265"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/next-environment/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "4a58ad31c388c892639d"
      GITHUB_REDIRECT_URI: "https://server-next.amplication-dev.com/github/callback"

amplication-git-push-webhook-service:
  ingress:
    hostname: webhook-next.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-next-cp-kafka-headless:9092"]'
      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0
      KAFKA_CLIENT_ID: git-push-webhook-service
      KAFKA_GROUP_ID: amplication-git-push-webhook-service

amplication-git-pull-service:
  config:
    env:
      NODE_ENV: "production"

      #EFS
      STORAGE_PATH: /amplication-data/git-data
      MAX_SNAPSHOTS: "100"

      #GitHub App
      GITHUB_APP_APP_ID: "225471"
      GITHUB_APP_CLIENT_ID: "Iv1.ba108fc312eb8265"
      GIT_DEFAULT_ORIGIN_NAME: origin

      KAFKA_BROKERS: '["amplication-next-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: git-pull-service
      KAFKA_GROUP_ID: git-pull-service-group

      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS: '["amplication-next-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: git-pull-request-service
      KAFKA_GROUP_ID: git-pull-request-service-group

      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
      CREATE_PULL_REQUEST_COMPLETED_TOPIC: git.internal.pull-request.completed.0
      
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      BUILD_OUTPUT_FOLDER: output
      GITHUB_APP_APP_ID: "225471"

amplication-storage-gateway:
  ingress:
    hostname: server-next.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-next-cp-kafka-headless:9092"]'
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      BUILD_OUTPUT_FOLDER: output
      GITHUB_APP_APP_ID: "225471"

amplication-build-manager:
  config:
    env:
      PORT: "80"

      KAFKA_BROKERS: '["amplication-next-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: build-manager
      KAFKA_GROUP_ID: build-manager

      CREATE_PR_REQUEST_TOPIC: internal.create-pr.request.0
      CODE_GENERATION_REQUEST_TOPIC: internal.code-generation.request.0
      CODE_GENERATION_SUCCESS_TOPIC: internal.code-generation.success.0
      CODE_GENERATION_FAILURE_TOPIC: internal.code-generation.failure.0

      DSG_RUNNER_URL: http://localhost:12000/example

      BASE_BUILDS_FOLDER: /amplication-data/build-data
      RESOURCE_DATA_FILE_NAME: input.json

