amplication-client:
  deployment:
    image:
      repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-client-dev
  service:
    hostname: app.staging-os.amplication-dev.com
  config:
    env:
      REACT_APP_DATA_SOURCE: "https://server.staging-os.amplication-dev.com/graphql"
      REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server.staging-os.amplication-dev.com/github"
amplication-server:
  deployment:
    image:
      repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-server-dev
  postgres:
    install: false
  ingress:
    enabled: true
    hostname: server.staging-os.amplication-dev.com
  config:
    env:
      GITHUB_APP_APP_ID: "189214"
      CONTAINER_BUILDER_DEFAULT: docker
      GITHUB_APP_CLIENT_ID: "Iv1.7eb319d8e3c170d7"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/amplication-aws/installations/new?state={state}"
      GITHUB_REDIRECT_URI: "https://server.staging-os.amplication-dev.com/github/callback"
      GITHUB_SECRET_SECRET_NAME: "projects/948093699220/secrets/github-secret-amplication-aws/versions/1"
      HOST: "https://server.staging-os.amplication-dev.com"
      GITHUB_CLIENT_ID: "aa4d2f3ccd7d47cbbf71"
