global:
  pvc:
    name: build-artifacts
    storageRequest: 5Gi
    storageName: efs-sc
  pv:
    name: build-artifacts-eugene
    storageCapacity: 5Gi
    handle: fs-03a0a5ba30d788595::fsap-08494d4659781878b

  nodeSelector:
    role: custom-envs
  tolerations:
    - key: "custom-envs"
      operator: "Equal"
      value: "true"

postgres:
  primary:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres-eugene.amplication-dev.com

amplication-client:
  service:
    hostname: app-eugene.amplication-dev.com
  config:
    env:
      NX_REACT_APP_SERVER_URI: "https://server-eugene.amplication-dev.com"
      NX_REACT_APP_DATA_SOURCE: "https://server-eugene.amplication-dev.com/graphql"
      NX_REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server-eugene.amplication-dev.com/github"
      NX_REACT_APP_STORAGE_GATEWAY_URL: https://server-eugene.amplication-dev.com

amplication-server:
  autoscaling:
    minReplicas: 4
    maxReplicas: 99
  replicaCount: 4
  ingress:
    hostname: server-eugene.amplication-dev.com
  config:
    env:
      HOST: "https://server-eugene.amplication-dev.com"
      CLIENT_HOST: "https://app-eugene.amplication-dev.com"

      #KAFKA
      KAFKA_BROKERS: 'amplication-eugene-cp-kafka-headless:9092'
      KAFKA_CLIENT_ID: amplication-server
      KAFKA_GROUP_ID: amplication-server-group

      CREATE_PR_REQUEST_TOPIC: git.internal.create-pr.request.1
      CREATE_PR_SUCCESS_TOPIC: git.internal.create-pr.success.1
      CREATE_PR_FAILURE_TOPIC: git.internal.create-pr.failure.1

      CODE_GENERATION_REQUEST_TOPIC: build.internal.code-generation.request.1
      CODE_GENERATION_SUCCESS_TOPIC: build.internal.code-generation.success.1
      CODE_GENERATION_FAILURE_TOPIC: build.internal.code-generation.failure.1

      DSG_LOG_TOPIC: build.internal.dsg-log.1

      DOCKER_HOST: tcp://docker:2375

      DSG_RUNNER_URL: http://webhook-eventsource-svc.eugene-dsg.svc.cluster.local:12000/example

      #GitHub App
      GITHUB_APP_APP_ID: "227239"
      GITHUB_APP_CLIENT_ID: "Iv1.67a34bd44a1938fb"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/eugene-tseitlin-github-app/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "fe0059c5fd76abbf7cb4"
      GITHUB_REDIRECT_URI: "https://server-eugene.amplication-dev.com/github/callback"

amplication-git-push-webhook-service:
  ingress:
    hostname: webhook-eugene.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: 'amplication-eugene-cp-kafka-headless:9092'
      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0
      KAFKA_CLIENT_ID: git-push-webhook-service
      KAFKA_GROUP_ID: amplication-git-push-webhook-service

amplication-git-pull-service:
  config:
    env:
      NODE_ENV: "production"

      #EFS
      STORAGE_PATH: /amplication-data/git-data
      MAX_SNAPSHOTS: "100"

      #GitHub App
      GITHUB_APP_APP_ID: "227239"
      GITHUB_APP_CLIENT_ID: "Iv1.67a34bd44a1938fb"
      GIT_DEFAULT_ORIGIN_NAME: origin

      KAFKA_BROKERS: 'amplication-eugene-cp-kafka-headless:9092'
      KAFKA_CLIENT_ID: git-pull-service
      KAFKA_GROUP_ID: git-pull-service-group

      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS: 'amplication-eugene-cp-kafka-headless:9092'
      KAFKA_CLIENT_ID: git-pull-request-service
      KAFKA_GROUP_ID: git-pull-request-service-group

      CREATE_PR_REQUEST_TOPIC: git.internal.create-pr.request.1
      CREATE_PR_SUCCESS_TOPIC: git.internal.create-pr.success.1
      CREATE_PR_FAILURE_TOPIC: git.internal.create-pr.failure.1

      BUILD_ARTIFACTS_BASE_FOLDER: /amplication-data/build-data
      BUILD_ARTIFACTS_CODE_FOLDER: code

      GITHUB_APP_APP_ID: "227239"

amplication-storage-gateway:
  ingress:
    hostname: server-eugene.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: 'amplication-eugene-cp-kafka-headless:9092'
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      BUILD_OUTPUT_FOLDER: code
      GITHUB_APP_APP_ID: "227239"
