global:
  pvc:
    name: shimi-efs-claim
  pv:
    name: efs-pv-shimi
  nodeSelector:
    role: custom-envs
  tolerations:
    - key: "custom-envs"
      operator: "Equal"
      value: "true"

postgres:
  primary:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres-shimi.amplication-dev.com

amplication-client:
  service:
    hostname: app-shimi.amplication-dev.com
  config:
    env:
      REACT_APP_SERVER_URI: "https://server-shimi.amplication-dev.com"
      REACT_APP_DATA_SOURCE: "https://server-shimi.amplication-dev.com/graphql"
      REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server-shimi.amplication-dev.com/github"
      REACT_APP_STORAGE_GATEWAY_URL: https://server-shimi.amplication-dev.com

amplication-server:
  ingress:
    hostname: server-shimi.amplication-dev.com
  config:
    env:
      HOST: "https://server-shimi.amplication-dev.com"
      CLIENT_HOST: "https://app-shimi.amplication-dev.com"

      #KAFKA
      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
      KAFKA_BROKERS: '["amplication-shimi-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: amplication-server
      KAFKA_GROUP_ID: amplication-server-group

      #EFS
      BASE_BUILDS_FOLDER: /amplication-data/build-data

      #GCP - APPS Builder

      DEFAULT_DISK: gcs
      LOCAL_DISK_ROOT: /artifacts
      CONTAINER_BUILDER_DEFAULT: cloud-build
      GCS_BUCKET: amplication-artifacts

      #GCP - APPS Deployer
      DEPLOYER_DEFAULT: gcp

      GCP_APPS_PROJECT_ID: amplication-apps
      GCP_APPS_REGION: us-east1
      GCP_APPS_TERRAFORM_STATE_BUCKET: amplication-apps-state-bucket
      GCP_APPS_DATABASE_INSTANCE: apps-database-instance
      GCP_APPS_DOMAIN: staging.amplication.app

      DOCKER_HOST: tcp://docker:2375

      #GitHub App
      GITHUB_APP_APP_ID: "208482"
      GITHUB_APP_CLIENT_ID: "Iv1.88cfcc5cad0fab3e"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/shimienvamplication/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "d70e0863aea6de91da69"
      GITHUB_REDIRECT_URI: "https://server-shimi.amplication-dev.com/github/callback"

amplication-git-push-webhook-service:
  ingress:
    hostname: webhook-shimi.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-shimi-cp-kafka-headless:9092"]'
      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0
      KAFKA_CLIENT_ID: git-push-webhook-service
      KAFKA_GROUP_ID: amplication-git-push-webhook-service

amplication-git-pull-service:
  config:
    env:
      NODE_ENV: "production"

      #EFS
      STORAGE_PATH: /amplication-data/git-data
      MAX_SNAPSHOTS: "100"

      #GitHub App
      GITHUB_APP_APP_ID: "208482"
      GITHUB_APP_CLIENT_ID: "Iv1.88cfcc5cad0fab3e"
      GIT_DEFAULT_ORIGIN_NAME: origin

      KAFKA_BROKERS: '["amplication-shimi-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: git-pull-service
      KAFKA_GROUP_ID: git-pull-service-group

      KAFKA_REPOSITORY_PUSH_QUEUE: git.external.push.event.0

amplication-git-pull-request-service:
  config:
    env:
      KAFKA_BROKERS: '["amplication-shimi-cp-kafka-headless:9092"]'
      KAFKA_CLIENT_ID: git-pull-request-service
      KAFKA_GROUP_ID: git-pull-request-service-group
      GENERATE_PULL_REQUEST_TOPIC: git.internal.pull-request.request.0
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      GITHUB_APP_APP_ID: "208482"

amplication-storage-gateway:
  ingress:
    hostname: server-shimi.amplication-dev.com
  config:
    env:
      KAFKA_BROKERS: '["amplication-shimi-cp-kafka-headless:9092"]'
      BASE_BUILDS_FOLDER: /amplication-data/build-data
      GITHUB_APP_APP_ID: "208482"
