global:
  pvc:
    name: mor-efs-claim
  pv:
    name: efs-pv-mor
  nodeSelector:
    role: custom-envs
  tolerations:
    - key: "custom-envs"
      operator: "Equal"
      value: "true"

    
postgres:
  primary:
    service:
      annotations:
        external-dns.alpha.kubernetes.io/hostname: postgres-mor.amplication-dev.com

amplication-client:
  service:
    hostname: app-custom.amplication-dev.com
  config:
    env:
      NX_REACT_APP_DATA_SOURCE: "https://server-custom.amplication-dev.com/graphql"
      NX_REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "https://server-custom.amplication-dev.com/github"
      NX_REACT_APP_GITHUB_CLIENT_ID: value

amplication-server:
  ingress:
    hostname: server-custom.amplication-dev.com
  config:
    env:

      HOST: "https://server-custom.amplication-dev.com"
      CLIENT_HOST: 'https://app-custom.amplication-dev.com'

      DOCKER_HOST: tcp://docker:2375

      #GitHub App
      GITHUB_APP_APP_ID: "195638"
      GITHUB_APP_CLIENT_ID: "Iv1.7c4ec6671b7c8cd7"
      GITHUB_APP_INSTALLATION_URL: "https://github.com/apps/amplicaiton-server-staging-os/installations/new?state={state}"

      #GitHub OAuth App
      GITHUB_CLIENT_ID: "aa4d2f3ccd7d47cbbf71"
      GITHUB_SECRET_SECRET_NAME: "projects/948093699220/secrets/github-secret-amplication-aws/versions/1"
      GITHUB_REDIRECT_URI: "https://server-custom.amplication-dev.com/github/callback"