name: amplication-client

replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
image:
  pullPolicy: Always
  repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-prod-client
  tag: 0.0.1
  imagePullSecrets: []

service:
  type: LoadBalancer
  port:
    target: 8080
  protocol: TCP
  hostname: app.amplication-dev.com
  certificatearn: arn:aws:acm:us-east-1:407256539111:certificate/bc3442ea-ddcb-4870-b4ba-79144e623d71

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

maxMemory: "1.6Gi"
minMemory: "1.6Gi"
maxCPU: "0.9"
minCPU: "0.9"

config:
  env:
    REACT_APP_SERVER_URI: https://server.amplication-dev.com
    REACT_APP_DATA_SOURCE: https://server.amplication-dev.com/graphql
    REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: https://server.amplication-dev.com/github
    REACT_APP_GITHUB_CLIENT_ID: a4e9055e5f21448d6de7
    REACT_APP_AMPLITUDE_API_KEY: P5sO0VHJJlCrBz9bPYhFgN94VwyTyxPO
