name: delete-ns
on:
  workflow_dispatch:
    inputs:
      namespace:
        type: choice
        description: Which namespace you want to delete
        default: shimi
        required: true
        options: 
        - shimi
        - mor
        - amit

jobs:
  delete-ns:
    runs-on: ubuntu-18.04
    steps:
      - name: install argocd
        id: install-argocd
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - name: argocd login
        env: 
          ARGO_CD_PASSWORD: ${{ secrets.AWS_STAGING_OS_ARGOCD }}
        run: |
          ARGO_CD_URL="argocd.staging-os.amplication-dev.com"
          argocd login $ARGO_CD_URL --username admin --password $ARGO_CD_PASSWORD --grpc-web
      - name: delete ns
        env:
          NAMESPACE: ${{ github.event.inputs.namespace }}
        run: |
          APPNAME="amplication-$NAMESPACE"
          set +e
          argocd app delete $APPNAME





