name: DSG Version Tagger

on:
  push:
    paths:
      - packages/data-service-generator/package.json

permissions:
  contents: write
    
env:
  DSG_PACKAGE_JSON: packages/data-service-generator/package.json

jobs:
  dsg-version-tagger:
    name: Tag DSG Version Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: get-version
        name: Get current package.json version
        run: |
          echo "::set-output name=version::$(cat $DSG_PACKAGE_JSON  | jq -r '.version')"
      - name: Create git tag for version 
        id: tag-version
        run: |
          echo "üè∑Ô∏è Tagging ${{ github.sha }} with version ${{ steps.get-version.outputs.version }}"
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/git/refs \
            -d '{"ref":"refs/tags/dsg/v${{ steps.get-version.outputs.version }}","sha":"${{ github.sha }}"}'


