name: New Issue Automation
on:
  issues:
    types:
      - opened
      - reopened
      - closed

env:
  ISSUE_PROJECT_ID: 2
  ORG: amplication
  OPENED_REOPEND_STATUS: New
  CLOSED_STATUS: Closed

jobs:
  issue_closed:
    name: issue_closed
    runs-on: ubuntu-18.04
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: 'Moved issue to "Closed"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.2
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: ${{ env.ORG }}
          project_id: ${{ env.ISSUE_PROJECT_ID }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.CLOSED_STATUS }}
