name: New Issue Automation
on:
  issues:
    types:
      - opened
      - reopened
      - closed

env:
  ISSUE_PROJECT_ID: 2
  ORG: amplication
  OPENED_REOPEND_STATUS: New
  CLOSED_STATUS: Closed

jobs:
  issue_opened_and_reopened:
    name: issue_opened_and_reopened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened' || github.event.action == 'reopened'
    steps:
      - name: 'Move issue to "New"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.2
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: ${{ env.ORG }}
          project_id: ${{ env.ISSUE_PROJECT_ID }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.OPENED_REOPEND_STATUS }}
      - name: 'Discord notification'
        uses: Ilshidur/action-discord@0.3.2
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"color":3447003,"title":"${{ github.event.issue.title}} #${{github.event.issue.number}}","url":"${{ github.event.issue.html_url }}","author":{"name":"${{ github.event.issue.user.login }}","icon_url":"${{ github.event.issue.user.avatar_url }}","url":"${{ github.event.issue.user.html_url }}"},"description":"Issue - ${{ github.event.action }}"}]'

  issue_closed:
    name: issue_closed
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'closed'
    steps:
      - name: 'Moved issue to "Closed"'
        uses: leonsteinhaeuser/project-beta-automations@v1.0.2
        with:
          gh_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          organization: ${{ env.ORG }}
          project_id: ${{ env.ISSUE_PROJECT_ID }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.CLOSED_STATUS }}